import { IBase, IBeneficiary, IPagination } from "../../../../base";
import { IProvider } from "../../Rate";

export interface ITransaction extends IBase {
  id: string;
  trxn_id: string;
  user_id: string;
  bank_name: null;
  transaction_type_id: string;
  currency_id: string;
  transaction_status_id: string;
  beneficiary_id: null;
  invoice_document_id: null;
  crypto_liquidity_purchase_id: null;
  fiat_liquidity_purchase_id: null;
  rail_settlement_id: null;
  created_at: Date;
  updated_at: Date;
  sender_name: string;
  amount: number;
  recipient_amount: number;
  transactionType: ITransactionType;
  transactionStatus: ITransactionStatus;
  currency: ICurrency;
  beneficiary: IBeneficiary;
  derivedPrice: IDerivedPrice;
}

export interface ITransactionData {
  transactions: ITransaction[];
  pagination: IPagination;
}

export interface ITransactionType {
  created_at: string;
  deleted_at: null;
  id: string;
  name: "wallet" | "exchange";
  slug: string;
  updated_at: string;
}

export interface ITransactionStatus {
  created_at: string;
  deleted_at: null;
  id: string;
  name: string;
  slug: string;
  updated_at: string;
}

// Generated by https://quicktype.io

export interface ICurrency {
  id: string;
  name: string;
  symbol: string;
  slug: string;
  created_at: string;
  updated_at: string;
}

export interface TransactionQuery {
  type?: string;
  status?: string;
  userId?: string;
  page?: number;
  size?: number;
}

export interface IDerivedPrice extends IBase {
  derived_amount: number;
  request_amount: number;
  from_currency_id: string;
  to_currency_id: string;
  buy_currency_id: string;
  type: string;
  wallet_funding_charge_ngn: number;
  zigah_rate: number;
  zigah_charge: number;
  zigah_percentage: number;
  zigah_profit: number;
  provider_id: string;
  provider: IProvider;
}
