import { IBeneficiary, IPagination } from "../../../../base";

export interface ITransaction {
  id: string;
  trxn_id: string;
  user_id: string;
  bank_name: null;
  transaction_type_id: string;
  currency_id: string;
  transaction_status_id: string;
  beneficiary_id: null;
  invoice_document_id: null;
  crypto_liquidity_purchase_id: null;
  fiat_liquidity_purchase_id: null;
  rail_settlement_id: null;
  created_at: Date;
  updated_at: Date;
  sender_name: string;
  amount: number;
  recipient_amount: number;
  transactionType: ITransactionType;
  transactionStatus: ITransactionStatus;
  currency: ICurrency;
  beneficiary: IBeneficiary;
}

export interface ITransactionData {
  transactions: ITransaction[];
  pagination: IPagination;
}

export interface ITransactionType {
  created_at: string;
  deleted_at: null;
  id: string;
  name: "wallet" | "exchange";
  slug: string;
  updated_at: string;
}

export interface ITransactionStatus {
  created_at: string;
  deleted_at: null;
  id: string;
  name: string;
  slug: string;
  updated_at: string;
}

// Generated by https://quicktype.io

export interface ICurrency {
  id: string;
  name: string;
  symbol: string;
  slug: string;
  created_at: string;
  updated_at: string;
}


export interface TransactionQuery {
  type?: string;
  status?: string;
  userId?: string;
  page?: number;
  size?: number;
}
